Import('env')

lib_name='cyberland_rm'

#Sources to generate the library
source_files=[
    'Request.cpp',
    'RequestManager.cpp',
    'RequestManagerVirtualMachine.cpp'
]

# Build library
env.StaticLibrary(lib_name, source_files)
